# Generated by Django 3.2.18 on 2023-03-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230321_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipesingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipesingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipestags',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipestags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='RecipesIngredients',
        ),
        migrations.DeleteModel(
            name='RecipesTags',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
